/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  core: {
    HealthChecks: () => import('#app/core/controllers/health_checks_controller'),
  },
  identity: {
    Auth: () => import('#app/identity/controllers/auth_controller'),
  },
}
